# このファイルは tecsgen により自動生成されました
# Makefile.temp は gen の一つ上のディレクトリに移して使用します
#  % mv Makefile.temp Makefile
# 
# clean のデフォルト動作は $(GEN_DIR)/Makefile.* を削除します

# 変数 #_MVAR_#
TARGET = attribute.exe
TECSGEN_EXE = tecsgen
CC = gcc -g
CFLAGS = -I . -I ../RUNTIME/tecs-runtime/include/ -I ../RUNTIME/tecs-runtime/workaround/ -I ../RUNTIME/tecs-runtime/target/ -I gen -I src
LD = gcc
LDFLAGS = 
GEN_DIR = gen
SRC_DIR = src
vpath %.c $(SRC_DIR) $(GEN_DIR)

# ルール #_MRUL_#
no_target :
	@echo "no target specified"
	@echo "at first or when edit .cdl files, do below"
	@echo "% make tecsgen"
	@echo "at second, do below"
	@echo "% make all"
	@echo "to clean"
	@echo "% make clean"

all : $(TARGET) 


# depend を include #_MDEP_#
-include gen/Makefile.tecsgen
-include gen/Makefile.depend

$(TARGET) : tecsgen.timestamp $(CELLTYPE_COBJS) $(TECSGEN_COBJS) $(PLUGIN_COBJS)
	$(LD) $(LDFLGAS) -o $(TARGET) $(TECSGEN_COBJS) $(CELLTYPE_COBJS) $(PLUGIN_COBJS)

# For temporal construction using template code.
TEMPL_COBJS = \
 	$(GEN_DIR)/tAttribute_templ.o \
 	$(GEN_DIR)/tAttributeSt_templ.o \
 	$(GEN_DIR)/tMain_templ.o \
# TEMPL_COBJS terminater

TEMPL_SRCS = \
 	$(GEN_DIR)/tAttribute_templ.c \
 	$(GEN_DIR)/tAttributeSt_templ.c \
 	$(GEN_DIR)/tMain_templ.c \
# TEMPL_SRCS terminater

# テンプレートコードでメークしてみる場合 #_TCM_#
# $(TARGET) : tecsgen.timestamp $(TECSGEN_COBJS) $(TEMPL_COBJS) $(PLUGIN_COBJS)
#	$(LD) $(LDFLGAS) -o $(TARGET) $(TECSGEN_COBJS) $(TEMPL_COBJS) $(PLUGIN_COBJS)

clean :
	rm -rf $(GEN_DIR)
	rm -f $(TECS_COBJS)
	rm -f $(TARGET)
	rm -f tecsgen.timestamp

tecsgen : tecsgen.timestamp

tecsgen.timestamp : $(TECS_IMPORTS)
	# $(TECSGEN_EXE) -R -I ../RUNTIME/tecs-runtime/include/ -I ../RUNTIME/tecs-runtime/workaround/ -I ../RUNTIME/tecs-runtime/target/ -I src -R attribute.cdl
	$(TECSGEN_EXE) -I ../RUNTIME/tecs-runtime/include/ -I ../RUNTIME/tecs-runtime/workaround/ -I ../RUNTIME/tecs-runtime/target/ -I src attribute.cdl
	touch tecsgen.timestamp

# Celltype: tAttribute
$(GEN_DIR)/tAttribute_tecsgen.o : $(GEN_DIR)/tAttribute_tecsgen.c
	$(CC) -c $(CFLAGS) -o $@ $<

$(GEN_DIR)/tAttribute_templ.o : $(GEN_DIR)/tAttribute_templ.c
	$(CC) -c $(CFLAGS) -o $@ $<

tAttribute.o : tAttribute.c
	$(CC) -c $(CFLAGS) -o $@ $<

# Celltype: tAttributeSt
$(GEN_DIR)/tAttributeSt_tecsgen.o : $(GEN_DIR)/tAttributeSt_tecsgen.c
	$(CC) -c $(CFLAGS) -o $@ $<

$(GEN_DIR)/tAttributeSt_templ.o : $(GEN_DIR)/tAttributeSt_templ.c
	$(CC) -c $(CFLAGS) -o $@ $<

tAttributeSt.o : tAttributeSt.c
	$(CC) -c $(CFLAGS) -o $@ $<

# Celltype: tMain
$(GEN_DIR)/tMain_tecsgen.o : $(GEN_DIR)/tMain_tecsgen.c
	$(CC) -c $(CFLAGS) -o $@ $<

$(GEN_DIR)/tMain_templ.o : $(GEN_DIR)/tMain_templ.c
	$(CC) -c $(CFLAGS) -o $@ $<

tMain.o : tMain.c
	$(CC) -c $(CFLAGS) -o $@ $<

