# このファイルは tecsgen により自動生成されました
# Makefile.temp は gen の一つ上のディレクトリに移して使用します
#  % mv Makefile.temp Makefile
# 
# clean のデフォルト動作は $(GEN_DIR)/Makefile.* を削除します

# 変数 #_MVAR_#
TARGET = attribute-ROM.exe
TIMESTAMP = tecsgen.timestamp.ROM
TECSGEN_EXE = tecsgen
BASE_DIR = .
CC = gcc
# CFLAGS = -I $(BASE_DIR)/. -I $(BASE_DIR)/../RUNTIME/tecs-runtime/include/ -I $(BASE_DIR)/../RUNTIME/tecs-runtime/workaround/ -I $(BASE_DIR)/../RUNTIME/tecs-runtime/target/ -I $(BASE_DIR)/src -I $(GEN_DIR)
CFLAGS = -I $(BASE_DIR)/. -I $(BASE_DIR)/../RUNTIME/tecs-runtime/target/ -I $(BASE_DIR)/../RUNTIME/tecs-runtime/include/ -I $(BASE_DIR)/src -I $(GEN_DIR)
LD = gcc
LDFLAGS = 
GEN_DIR = $(BASE_DIR)/gen.ROM
SRC_DIR = $(BASE_DIR)/src
_TECS_OBJ_DIR = $(GEN_DIR)/
#   _TECS_OBJ_DIR   # should be end with '/'

vpath %.c $(SRC_DIR) $(GEN_DIR)
vpath %.h $(SRC_DIR) $(GEN_DIR)

OTHER_OBJS =                       # Add objects out of tecs care.

# ルール #_MRUL_#
no_target :
	@echo "no target specified"
	@echo "at first or when edit .cdl files, do below"
	@echo "% make tecs"
	@echo "at second, do below"
	@echo "% make all"
	@echo "to clean"
	@echo "% make clean"

all : $(TARGET)


# depend を include #_MDEP_#
-include $(GEN_DIR)/Makefile.tecsgen
-include $(GEN_DIR)/Makefile.depend

$(TARGET) : $(TIMESTAMP) $(CELLTYPE_COBJS) $(TECSGEN_COBJS) $(PLUGIN_COBJS) $(OTHER_OBJS)
	$(LD) $(LDFLAGS) -o $(TARGET) $(TECSGEN_COBJS) $(CELLTYPE_COBJS) $(PLUGIN_COBJS) $(OTHER_OBJS)

clean :
	rm -f $(CELLTYPE_COBJS) $(TECSGEN_COBJS) $(PLUGIN_COBJS) $(OTHER_OBJS) $(TARGET)  $(TIMESTAMP)
	rm -rf $(GEN_DIR)

tecs : $(TIMESTAMP)

$(TIMESTAMP) : $(TECS_IMPORTS)
	$(TECSGEN_EXE)  -g $(GEN_DIR) -I ../RUNTIME/tecs-runtime/include/ -I ../RUNTIME/tecs-runtime/workaround/ -I ../RUNTIME/tecs-runtime/target/ -I src -R attribute.cdl
	touch $(TIMESTAMP)

# generic target for objs
$(_TECS_OBJ_DIR)%.o : %.c
	$(CC) -c $(CFLAGS) -o $@ $<

tAttribute.o : tAttribute.c
	$(CC) -c $(CFLAGS) -o $@ $<
 
tAttributeSt.o : tAttributeSt.c
	$(CC) -c $(CFLAGS) -o $@ $<
 
tMain.o : tMain.c
	$(CC) -c $(CFLAGS) -o $@ $<
 
tCEXP.o : tCEXP.c
	$(CC) -c $(CFLAGS) -o $@ $<
 
tCelltype.o : tCelltype.c
	$(CC) -c $(CFLAGS) -o $@ $<
 
tAttribute2.o : tAttribute2.c
	$(CC) -c $(CFLAGS) -o $@ $<
 
