// BTstack - version.h
// - generated by ./../../tools/get_version.sh
// - at 2016-03-16_16:53:45
#define BTSTACK_MAJOR 0
#define BTSTACK_MINOR 9
#define BTSTACK_COMMIT "8a5706a"
#define BTSTACK_VERSION "0.9-8a5706a"
#define BTSTACK_DATE "2016-03-16_16:53:45"
