/*
 * This file was automatically generated by tecsgen.
 * Move and rename like below before editing,
 *   gen/tNonInline_template.c => src/tNonInline.c
 * to avoid to be overwritten by tecsgen.
 */
/* #[<PREAMBLE>]#
 * Don't edit the comments between #[<...>]# and #[</...>]#
 * These comment are used by tecsmerege when merging.
 *
 * call port function #_TCPF_#
 * call port: cInline2 signature: sInline2 context:task 
 *   void           cInline2_inline2( );
 *
 * #[</PREAMBLE>]# */

/* Put prototype declaration and/or variale definition here #_PAC_# */
#include "nInline_tNonInline_tecsgen.h"

#ifndef E_OK
#define	E_OK	0		/* success */
#define	E_ID	(-18)	/* illegal ID */
#endif

/* entry port function #_TEPF_# */
/* #[<ENTRY_PORT>]# eNonInline
 * entry port: eNonInline
 * signature:  sNonInline
 * context:    task
 * #[</ENTRY_PORT>]# */

/* #[<ENTRY_FUNC>]# eNonInline_nonInline
 * name:         eNonInline_nonInline
 * global_name:  nInline_tNonInline_eNonInline_nonInline
 * oneway:       false
 * #[</ENTRY_FUNC>]# */
void
eNonInline_nonInline(CELLIDX idx)
{
	CELLCB	*p_cellcb;
	if (VALID_IDX(idx)) {
		p_cellcb = GET_CELLCB(idx);
	}
	else {
		/* Write error processing code here */
	} /* end if VALID_IDX(idx) */

	/* Put statements here #_TEFB_# */

}

/* #[<POSTAMBLE>]#
 *   Put non-entry functions below.
 * #[</POSTAMBLE>]#*/
