/*
 * This file was automatically generated by tecsgen.
 * Move and rename like below before editing,
 *   gen/tInline_inline_template.h => src/tInline_inline.h
 * to avoid to be overwritten by tecsgen.
 */
/* #[<PREAMBLE>]#
 * Don't edit the comments between #[<...>]# and #[</...>]#
 * These comment are used by tecsmerege when merging.
 *
 * call port function #_TCPF_#
 * call port: cNonInline signature: sNonInline context:task 
 *   void           cNonInline_nonInline( );
 *
 * #[</PREAMBLE>]# */

/* entry port function #_TEPF_# */
/* #[<ENTRY_PORT>]# eInline1
 * entry port: eInline1
 * signature:  sInline1
 * context:    task
 * #[</ENTRY_PORT>]# */

/* #[<ENTRY_FUNC>]# eInline1_inline1
 * name:         eInline1_inline1
 * global_name:  nInline_tInline_eInline1_inline1
 * oneway:       false
 * #[</ENTRY_FUNC>]# */
Inline void
eInline1_inline1(CELLIDX idx)
{
	CELLCB	*p_cellcb;
	if (VALID_IDX(idx)) {
		p_cellcb = GET_CELLCB(idx);
	}
	else {
		/* Write error processing code here */
	} /* end if VALID_IDX(idx) */

	/* Put statements here #_TEFB_# */

}

/* #[<POSTAMBLE>]#
 *   Put non-entry functions below.
 * #[</POSTAMBLE>]#*/
