/*
 * This file was automatically generated by tecsgen.
 * Move and rename like below before editing,
 *   gen/tUserCelltypeA_template.c => src/tUserCelltypeA.c
 * to avoid to be overwritten by tecsgen.
 */
/* #[<PREAMBLE>]#
 * Don't edit the comments between #[<...>]# and #[</...>]#
 * These comment are used by tecsmerege when merging.
 *
 * #[</PREAMBLE>]# */

/* Put prototype declaration and/or variale definition here #_PAC_# */
#include "tUserCelltypeA_tecsgen.h"

#ifndef E_OK
#define	E_OK	0		/* success */
#define	E_ID	(-18)	/* illegal ID */
#endif

/* entry port function #_TEPF_# */
/* #[<ENTRY_PORT>]# eiHandlerBody1
 * entry port: eiHandlerBody1
 * signature:  siHandlerBody
 * context:    task
 * #[</ENTRY_PORT>]# */

/* #[<ENTRY_FUNC>]# eiHandlerBody1_main
 * name:         eiHandlerBody1_main
 * global_name:  tUserCelltypeA_eiHandlerBody1_main
 * oneway:       false
 * #[</ENTRY_FUNC>]# */
void
eiHandlerBody1_main(CELLIDX idx)
{
	CELLCB	*p_cellcb;
	if (VALID_IDX(idx)) {
		p_cellcb = GET_CELLCB(idx);
	}
	else {
		/* Write error processing code here */
	} /* end if VALID_IDX(idx) */

	/* Put statements here #_TEFB_# */

}

/* #[<ENTRY_PORT>]# eiHandlerBody2
 * entry port: eiHandlerBody2
 * signature:  siHandlerBody
 * context:    task
 * entry port array size:  NEP_eiHandlerBody2
 * #[</ENTRY_PORT>]# */

/* #[<ENTRY_FUNC>]# eiHandlerBody2_main
 * name:         eiHandlerBody2_main
 * global_name:  tUserCelltypeA_eiHandlerBody2_main
 * oneway:       false
 * #[</ENTRY_FUNC>]# */
void
eiHandlerBody2_main(CELLIDX idx, int_t subscript)
{
	CELLCB	*p_cellcb;
	if (VALID_IDX(idx)) {
		p_cellcb = GET_CELLCB(idx);
	}
	else {
		/* Write error processing code here */
	} /* end if VALID_IDX(idx) */

	/* Put statements here #_TEFB_# */

}

/* #[<ENTRY_PORT>]# eiHandlerBody3
 * entry port: eiHandlerBody3
 * signature:  siHandlerBody
 * context:    task
 * #[</ENTRY_PORT>]# */

/* #[<ENTRY_FUNC>]# eiHandlerBody3_main
 * name:         eiHandlerBody3_main
 * global_name:  tUserCelltypeA_eiHandlerBody3_main
 * oneway:       false
 * #[</ENTRY_FUNC>]# */
void
eiHandlerBody3_main(CELLIDX idx)
{
	CELLCB	*p_cellcb;
	if (VALID_IDX(idx)) {
		p_cellcb = GET_CELLCB(idx);
	}
	else {
		/* Write error processing code here */
	} /* end if VALID_IDX(idx) */

	/* Put statements here #_TEFB_# */

}

/* #[<ENTRY_PORT>]# eiHandlerBody4
 * entry port: eiHandlerBody4
 * signature:  siHandlerBody
 * context:    task
 * entry port array size:  NEP_eiHandlerBody4
 * #[</ENTRY_PORT>]# */

/* #[<ENTRY_FUNC>]# eiHandlerBody4_main
 * name:         eiHandlerBody4_main
 * global_name:  tUserCelltypeA_eiHandlerBody4_main
 * oneway:       false
 * #[</ENTRY_FUNC>]# */
void
eiHandlerBody4_main(CELLIDX idx, int_t subscript)
{
	CELLCB	*p_cellcb;
	if (VALID_IDX(idx)) {
		p_cellcb = GET_CELLCB(idx);
	}
	else {
		/* Write error processing code here */
	} /* end if VALID_IDX(idx) */

	/* Put statements here #_TEFB_# */

}

/* #[<POSTAMBLE>]#
 *   Put non-entry functions below.
 * #[</POSTAMBLE>]#*/
