.PHONY : all
all:
	make -f Makefile-normal
	make -f Makefile-r
	make -f Makefile-ram-initializer

.PHONY : tecs
tecs:
	make tecs -f Makefile-normal
	make tecs -f Makefile-r
	make tecs -f Makefile-ram-initializer

.PHONY : clean
clean:
	make clean -f Makefile-normal
	make clean -f Makefile-r
	make clean -f Makefile-ram-initializer
